### ISSUE TITLE
[repo] Couldn't deploy in GKE without vm.max_map_count

### ISSUE THREAD

**Issue by vinieger** [devops-ia/helm-opencti#187]
### Describe the bug a clear and concise description of what the bug is.

I was struggling to use the chart in GKE, the elastic search data and master pods was failing, so the opencti ones wouldn't start. Fixed by I set the kernel parameter 'vm.max_map_count' as per docs: https://docs.opencti.io/latest/deployment/installation/#pre-requisites:~:text=set%20vm.max_map_count

I did that via deploying the following daemonset, then killed the elastic search master pod:

```
# file: elasticsearch-sysctl.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: elasticsearch-sysctl
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: elasticsearch-sysctl
  template:
    metadata:
      labels:
        name: elasticsearch-sysctl
    spec:
      hostPID: true
      containers:
        - name: sysctl
          image: busybox
          command: ["sh", "-c", "sysctl -w vm.max_map_count=262144; sleep 3600"]
          securityContext:
            privileged: true
      tolerations:
        - operator: Exists
      nodeSelector: {}
```

### What's your helm version?

version.BuildInfo{Version:"v3.18.0", GitCommit:"cc58e3f5a3aa615c6a86275e6f4444b5fdd3cc4e", GitTreeState:"clean", GoVersion:"go1.24.3"}

### What's your kubectl version?

Client Version: v1.33.1 / Kustomize Version: v5.6.0 / Server Version: v1.32.4-gke.1236007

### Chart version

 v1.10.19

### Enter the command that you execute when chart failing/misfunctioning

helm install opencti opencti/opencti -f values.yaml --namespace default

**Comment by vinieger** [comment]
also, overriding the memory limits was necessary - otherwise I'd get OOMkilled on the elastic master - e.g.:

```
elasticsearch:
  enabled: true
  clusterName: opencti
  master:
    resources:
      limits:
        memory: "2Gi"
      requests:
        memory: "1Gi"
```
