### ISSUE TITLE
[opencti] Connectors

### ISSUE THREAD

**Issue by e4242** [devops-ia/helm-opencti#3]
### Describe the bug a clear and concise description of what the bug is.

Various errors from different connectors. For example, in import-file-stix:
```
Error: unable to import required numpy module.
See https://pypi.python.org/pypi/numpy.A TOKEN must be set
```
In alienvault, no logs. Just shows terminated.

### What's your helm version?

v3.14.4

### What's your kubectl version?

v1.29.3

### Chart version

latest

### Enter the changed values of values.yaml?

```
# Connectors
connectors:
- name: alienvault
  enabled: true
  replicas: 1
  image:
    repository: opencti/connector-alienvault
  env:
    CONNECTOR_CONFIDENCE_LEVEL: "50"
    CONNECTOR_ID: "d0fc7f7a-7710-4abd-9164-fe02b739737c"
    CONNECTOR_UPDATE_EXISTING_DATA: "false"
    CONNECTOR_LOG_LEVEL: "debug" # Empty use global config
    ALIENVAULT_BASE_URL: "https://otx.alienvault.com"
    ALIENVAULT_API_KEY: "REDUCTED"
    ALIENVAULT_TLP: "White"
    ALIENVAULT_CREATE_OBSERVABLES: "true"
    ALIENVAULT_CREATE_INDICATORS: "true"
    ALIENVAULT_PULSE_START_TIMESTAMP: "2024-05-01T00:00:00"
    ALIENVAULT_REPORT_TYPE: "threat-report"
    ALIENVAULT_REPORT_STATUS: "New"
    ALIENVAULT_GUESS_MALWARE: "false"
    ALIENVAULT_GUESS_CVE: "false"
    ALIENVAULT_EXCLUDED_PULSE_INDICATOR_TYPES: "FileHash-MD5,FileHash-SHA1"
    ALIENVAULT_ENABLE_RELATIONSHIPS: "true"
    ALIENVAULT_ENABLE_ATTACK_PATTERNS_INDICATES: "false"
    ALIENVAULT_INTERVAL_SEC: "1800"
    CONNECTOR_NAME: "AlienVault"
    CONNECTOR_SCOPE: "alienvault"
    CONNECTOR_TYPE: "EXTERNAL_IMPORT"
  resources:
    limits:
      memory: 512Mi
      cpu: 500m
    requests:
      memory: 256Mi
      cpu: 250m

- name: import-file-stix
  enabled: true
  replicas: 1
  image:
    repository: opencti/connector-import-file-stix
  env:
    CONNECTOR_CONFIDENCE_LEVEL: "70"
    CONNECTOR_ID: "d0fc7f7a-8710-4abd-9164-fe02b739737a"
    CONNECTOR_LOG_LEVEL: "debug" # Empty use global config
    CONNECTOR_NAME: ImportFileStix
    CONNECTOR_SCOPE: application/json,text/xml
    CONNECTOR_TYPE: INTERNAL_IMPORT_FILE
```

### Enter the command that you execute when chart failing/misfunctioning

helm install opencti opencti/opencti --values opencti/ci/ci-values-connector.yaml

### More info

Everything works fine except the connectors. Not sure what I'm doing wrong there.
