### ISSUE TITLE
Annotations failed

### ISSUE THREAD

**Issue by ialejandro** [devops-ia/helm-opencti#34]
I still have the error with this ver 😿, but my PR #32 has fixed it btw

my annotation:
```
connectors:
- name: splunk
  enabled: true
  replicas: 1
  podAnnotations:
    vault.security.banzaicloud.io/vault-addr: "https://vault.test:8200"
    vault.security.banzaicloud.io/vault-path: "kubernetes_itsec"
    vault.security.banzaicloud.io/vault-role: "opencti"
    vault.security.banzaicloud.io/vault-skip-verify: "true"
  image:
    repository: opencti/connector-splunk
    tag: "6.2.15"
    ...
```

```
 Error: Failed to render chart: exit status 1: Error: unable to build kubernetes objects from release manifest: error validating "":
 error validating data: [ValidationError(Deployment.spec.template.metadata.annotations.Capabilities): invalid type for
 io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta.annotations: got "map", expected "string", ValidationError(Deployment.spec.template.metadata.annotations.Chart): invalid type for io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta.annotations:
 got "map", expected "string", ValidationError(Deployment.spec.template.metadata.annotations.Files): invalid type for io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta.annotations: got "map", expected "string", ValidationError(
 Deployment.spec.template.metadata.annotations.Release): invalid type for io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta.annotations: got "map", expected "string", ValidationError(Deployment.spec.template.metadata.annotations.Subcharts): invalid type for 
 io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta.annotations: got "map", expected "string", ValidationError(
 Deployment.spec.template.metadata.annotations.Template): invalid type for 
 io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta.annotations: got "map", expected "string", ValidationError(
 Deployment.spec.template.metadata.annotations.Values): invalid type for io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta.annotations: 
 got "map", expected "string"]

```

_Originally posted by @r4zr1 in https://github.com/devops-ia/helm-opencti/issues/33#issuecomment-2311003686_
