### ISSUE TITLE
Connectors : OPENCTI_TOKEN not honored when set in envFromSecrets

### ISSUE THREAD

**Issue by acodefella** [devops-ia/helm-opencti#36]
### Describe the bug a clear and concise description of what the bug is.

In connectors, when OPENCTI_TOKEN is set in envFromSecrets and not hard-coded as part of env.  This line [here](https://github.com/acodefella/helm-opencti/blob/main/charts/opencti/templates/connector/deployment.yaml#L87), gets evaluated to TRUE.
Condition 1 : (not (hasKey .env "OPENCTI_TOKEN"))  : True because value is not hard-coded in env
Condition 2 : ($.Values.env.APP__ADMIN__TOKEN)  : True because of [default value ChangeMe](https://github.com/acodefella/helm-opencti/blob/main/charts/opencti/values.yaml#L54)

Thus, second instance of OPENCTI_TOKEN with "ChangeMe" takes precedence and connector errors out.

Whatever, I set in envFromSecrets OPENCTI_TOKEN is ignored.

Solution for this pbm is to use `$envList` instead of .env. Very similar to [worker deployment](https://github.com/acodefella/helm-opencti/blob/main/charts/opencti/templates/worker/deployment.yaml#L97).

### What's your helm version?

v3.15.4

### What's your kubectl version?

v1.30.4

### Chart version

1.0.0 (latest)

### Explain bug

Connector errors out without correct opencti_token

### What you expected to happen?

To honor OPENCTI_TOKEN set in envFromSecrets

### How to reproduce it?

 OPENCTI_TOKEN is set in envFromSecrets and not hard-coded as part of env

### Enter the changed values of values.yaml?

NONE

**Comment by acodefella** [comment]
@ialejandro, I'm working on PR to resolve this issue. will send it to you once it is ready.

**Comment by acodefella** [comment]
[Pull request 37](https://github.com/devops-ia/helm-opencti/pull/37) is submitted for your review @ialejandro .

**Comment by ialejandro** [comment]
Maybe we need to improve this codeblock for `worker` and `connectors`, because I already tested some cases:

@acodefella thx a lot for you helper! I'll try reproduce all posible cases, what case you mean?

1. Case: with `.env` (on template)

```yaml
env:
  APP__ADMIN__TOKEN: b1976749-8a53-4f49-bf04-cafa2a3458c1
...
secrets:
  OPENCTI_TOKEN: my-ci-cd
...
connectors:
- name: alienvault
  enabled: true
  replicas: 1
  env:
    OPENCTI_TOKEN: "issue-token"
```

Result:

```console
...
      containers:
        - name: alienvault-connector
          securityContext:
            null
          image: "opencti/alienvault:6.2.15"
          imagePullPolicy: IfNotPresent
          env:
          # Variables from secrets have precedence

          # Special handling for OPENCTI_URL which is constructed from other values
          - name: OPENCTI_URL
            value: "http://opencti-ci-server:80"

          # Special handling for OPENCTI_TOKEN which is constructed from other values

          # Add Variables in plain text if they were not already added from secrets
          - name: OPENCTI_TOKEN
            value: "issue-token"

          resources:
            null
```

2. Case: with `.env` (on template) and `.envFromSecrets` (on connector):

```yaml
env:
  APP__ADMIN__TOKEN: b1976749-8a53-4f49-bf04-cafa2a3458c1
...
secrets:
  OPENCTI_TOKEN: my-ci-cd
...
connectors:
- name: alienvault
  enabled: true
  replicas: 1
  env:
    OPENCTI_TOKEN: "issue-token"
  envFromSecrets:
    OPENCTI_TOKEN:
      name: opencti-ci-credentials
      key: OPENCTI_TOKEN
```

Result:

```console
...
      containers:
        - name: alienvault-connector
          securityContext:
            null
          image: "opencti/alienvault:6.2.15"
          imagePullPolicy: IfNotPresent
          env:
          # Variables from secrets have precedence
          - name: OPENCTI_TOKEN
            valueFrom:
              secretKeyRef:
                name: opencti-ci-credentials
                key: OPENCTI_TOKEN

          # Special handling for OPENCTI_URL which is constructed from other values
          - name: OPENCTI_URL
            value: "http://opencti-ci-server:80"

          # Special handling for OPENCTI_TOKEN which is constructed from other values

          # Add Variables in plain text if they were not already added from secrets
```

3. Case: with `$envList` (on template)

```yaml
env:
  APP__ADMIN__TOKEN: b1976749-8a53-4f49-bf04-cafa2a3458c1
...
secrets:
  OPENCTI_TOKEN: my-ci-cd
...
connectors:
- name: alienvault
  enabled: true
  replicas: 1
  env:
    OPENCTI_TOKEN: "issue-token"
```

Result:

Duplicate `OPENCTI_TOKEN`: **wrong**

```console
...
      containers:
        - name: alienvault-connector
          securityContext:
            null
          image: "opencti/alienvault:6.2.15"
          imagePullPolicy: IfNotPresent
          env:
          # Variables from secrets have precedence

          # Special handling for OPENCTI_URL which is constructed from other values
          - name: OPENCTI_URL
            value: "http://opencti-ci-server:80"

          # Special handling for OPENCTI_TOKEN which is constructed from other values
          - name: OPENCTI_TOKEN
            value: "b1976749-8a53-4f49-bf04-cafa2a3458c1"

          # Add Variables in plain text if they were not already added from secrets
          - name: OPENCTI_TOKEN
            value: "issue-token"
```

4. Case: with `$envList` (on template) and `.envFromSecrets` (on connector):

```yaml
env:
  APP__ADMIN__TOKEN: b1976749-8a53-4f49-bf04-cafa2a3458c1
...
secrets:
  OPENCTI_TOKEN: my-ci-cd
...
connectors:
- name: alienvault
  enabled: true
  replicas: 1
  env:
    OPENCTI_TOKEN: "issue-token"
  envFromSecrets:
    OPENCTI_TOKEN:
      name: opencti-ci-credentials
      key: OPENCTI_TOKEN
```

Result:

```console
...
      containers:
        - name: alienvault-connector
          securityContext:
            null
          image: "opencti/alienvault:6.2.15"
          imagePullPolicy: IfNotPresent
          env:
          # Variables from secrets have precedence
          - name: OPENCTI_TOKEN
            valueFrom:
              secretKeyRef:
                name: opencti-ci-credentials
                key: OPENCTI_TOKEN

          # Special handling for OPENCTI_URL which is constructed from other values
          - name: OPENCTI_URL
            value: "http://opencti-ci-server:80"

          # Special handling for OPENCTI_TOKEN which is constructed from other values

          # Add Variables in plain text if they were not already added from secrets
```
