### ISSUE TITLE
Add NetworkPolicies

### ISSUE THREAD

**Issue by ialejandro** [devops-ia/helm-opencti#53]
Allow https://kubernetes.io/docs/concepts/services-networking/network-policies/ to improve network traffic and security

Sample:

```yaml
# -- NetworkPolicy parameters
# </br> Ref: https://kubernetes.io/docs/concepts/services-networking/network-policies/
networkPolicy:
  # -- Specifies whether a NetworkPolicy
  enabled: false
  # -- Ingress Rules
  ingressRules:
    # Namespace selector label allowed to access
    namespaceSelector: {}
    # Pod selector label allowed to access
    podSelector: {}
    # Additional custom ingress rules
    customRules: []
     #  - to:
     #     - namespaceSelector:
     #          matchLabels:
     #            label: example
  # -- Egress Rules
  egressRules:
    # Deny external connections
    denyConnectionsToExternal: false
    # Additional custom egress rules
    customRules: []
     #  - to:
     #     - namespaceSelector:
     #          matchLabels:
     #            label: example
```
