### ISSUE TITLE
[repo] APP__HEALTH_ACCESS_KEY wrong when applied from envFromSecrets

### ISSUE THREAD

**Issue by nathan-bowman** [devops-ia/helm-opencti#59]
### Describe the bug a clear and concise description of what the bug is.

When I apply `APP__HEALTH_ACCESS_KEY` in [values.yaml](https://github.com/devops-ia/helm-opencti/blob/v1.5.2/charts/opencti/values.yaml#L75) it builds [deployments.yaml](https://github.com/devops-ia/helm-opencti/blob/main/charts/opencti/templates/server/deployment.yaml#L111) by referencing `.Values.env.APP__HEALTH_ACCESS_KEY`.

Since I populate `APP__HEALTH_ACCESS_KEY` from `envFromSecrets` the wrong key is set...

values.yaml:
```
envFromSecrets:
  APP__HEALTH_ACCESS_KEY:
    name: opencti-credentials
    key: APP__HEALTH_ACCESS_KEY
```

The resultant deployment.yaml is:
```
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health?health_access_key=ChangeMe
              port: 4000
              scheme: HTTP
            initialDelaySeconds: 180
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
```

Logs do not show that the probes are failing because the health access key is actually different, just that the pod is killed:
```
{"category":"APP","level":"info","message":"[OPENCTI] SIGTERM signal received, stopping OpenCTI","source":"backend","timestamp":"2024-09-10T14:36:32.507Z","version":"6.2.18"}
```

### What's your helm version?

v3.15.4

### What's your kubectl version?

v1.31.0

### Chart version

v1.5.2

### Enter the command that you execute when chart failing/misfunctioning

N/A

**Comment by ialejandro** [comment]
Implement this usecase is impossible for now, I can provide you a workaround. I though to use `.Values.secrets.<key>` , but its not sense to do it, you can cipher directly `.Values.env.<key>` If you use SOPS, for example.

```yaml
env:
  APP__HEALTH_ACCESS_KEY: <uuid-gen>
  ...
```

But, for now, its no possible lookup a secret to set directly the content of this value on these probes.
